name: Publish package to GitHub Packages

on:
    push:
        branches: [ "api-client-library" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: '8.0.x'
      - name: Restore solution
        run: dotnet restore
      - name: Build solution
        run: dotnet build

      - name: Install client dependencies
        working-directory: ./client/API
        run: yarn

      - name: Build package
        working-directory: ./client/API
        run: yarn build
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@testnpmclient"
          
      - name: Publish package
        run: npm publish
        working-directory: ./client/API
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}